name: jlt_app_theme_handler
description: "A custom solution to handling themes across the JLT software suite."
version: 0.0.2
homepage:

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\Poppins-Thin.ttf
          weight: 100
        - asset: assets\fonts\Poppins-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets\fonts\Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets\fonts\Poppins-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets\fonts\Poppins-Light.ttf
          weight: 300
        - asset: assets\fonts\Poppins-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets\fonts\Poppins-Regular.ttf
          weight: 400
        - asset: assets\fonts\Poppins-Medium.ttf
          weight: 500
        - asset: assets\fonts\Poppins-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets\fonts\Poppins-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Poppins-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets\fonts\Poppins-Bold.ttf
          weight: 700
        - asset: assets\fonts\Poppins-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets\fonts\Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets\fonts\Poppins-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets\fonts\Poppins-Black.ttf
          weight: 900
        - asset: assets\fonts\Poppins-BlackItalic.ttf
          style: italic
          weight: 900
